export const recipes = [
    {
      id: 1,
      title: 'Classic Margherita Pizza',
      description: 'A traditional Italian pizza with fresh mozzarella, tomatoes, and basil.',
      imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1470&auto=format',
      prepTime: 20,
      cookTime: 15,
      servings: 4,
      cuisine: 'Italian',
      mealType: 'Dinner',
      ingredients: [
        '1 pizza dough',
        '1/4 cup tomato sauce',
        '8 oz fresh mozzarella, sliced',
        'Fresh basil leaves',
        '2 tbsp olive oil',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 475°F (245°C).',
        'Roll out the pizza dough on a floured surface.',
        'Spread tomato sauce evenly over the dough.',
        'Arrange mozzarella slices on top.',
        'Bake for 12–15 minutes until crust is golden.',
        'Remove from oven and top with fresh basil leaves.',
        'Drizzle with olive oil and season with salt and pepper.',
        'Slice and serve immediately.',
      ],
      isFavorite: false,
    },
    {
      id: 2,
      title: 'Chicken Alfredo Pasta',
      description: 'Creamy Alfredo sauce with grilled chicken over fettuccine noodles.',
      imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0V_TNEguGY0A2n41_RDmFqme89bLus__UVmTJXKaWXw&s',
      prepTime: 10,
      cookTime: 25,
      servings: 3,
      cuisine: 'Italian',
      mealType: 'Lunch',
      ingredients: [
        '8 oz fettuccine',
        '1 chicken breast, grilled and sliced',
        '1 cup heavy cream',
        '1/2 cup parmesan cheese',
        '2 tbsp butter',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Cook fettuccine according to package instructions.',
        'In a pan, melt butter and add cream.',
        'Stir in parmesan cheese and let it thicken.',
        'Add sliced chicken and cooked pasta.',
        'Toss everything well and season.',
      ],
      isFavorite: false,
    },
    {
      id: 3,
      title: 'Avocado Toast',
      description: 'Crunchy toast with creamy avocado and a sprinkle of chili flakes.',
      imageUrl: 'https://cookieandkate.com/images/2012/04/avocado-toast-recipe-3.jpg',
      prepTime: 5,
      cookTime: 5,
      servings: 2,
      cuisine: 'American',
      mealType: 'Breakfast',
      ingredients: [
        '2 slices whole grain bread',
        '1 ripe avocado',
        'Chili flakes',
        'Salt and pepper',
        'Lemon juice',
      ],
      instructions: [
        'Toast the bread until golden.',
        'Mash avocado with lemon juice, salt, and pepper.',
        'Spread the mixture on toast.',
        'Sprinkle chili flakes and serve.',
      ],
      isFavorite: false,
    },
    {
      id: 4,
      title: 'Berry Smoothie',
      description: 'A refreshing blend of mixed berries and yogurt.',
      imageUrl: 'https://cookieandkate.com/images/2018/05/best-blueberry-smoothie-recipe-1.jpg',
      prepTime: 5,
      cookTime: 0,
      servings: 1,
      cuisine: 'American',
      mealType: 'Shakes',
      ingredients: [
        '1 cup mixed berries',
        '1/2 cup plain yogurt',
        '1/2 cup milk',
        '1 tsp honey',
      ],
      instructions: [
        'Combine all ingredients in a blender.',
        'Blend until smooth.',
        'Serve chilled.',
      ],
      isFavorite: false,
    },
    {
      id: 5,
      title: 'Grilled Cheese Sandwich',
      description: 'Golden toasted bread with melted cheese.',
      imageUrl: 'https://cookieandkate.com/images/2019/04/best-grilled-cheese-sandwich-recipe-1-3.jpg',
      prepTime: 5,
      cookTime: 10,
      servings: 1,
      cuisine: 'American',
      mealType: 'Lunch',
      ingredients: [
        '2 slices of bread',
        '2 slices of cheddar cheese',
        '1 tbsp butter',
      ],
      instructions: [
        'Butter the outside of each bread slice.',
        'Place cheese between the unbuttered sides.',
        'Grill in a pan until golden and melty.',
      ],
      isFavorite: false,
    },
    {
      id: 6,
      title: 'Pancakes',
      description: 'Fluffy pancakes served with maple syrup.',
      imageUrl: 'https://cookieandkate.com/images/2024/05/almond-flour-pancakes.jpg',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      mealType: 'Breakfast',
      ingredients: [
        '1 cup flour',
        '2 tbsp sugar',
        '1 egg',
        '1 cup milk',
        '2 tbsp butter',
      ],
      instructions: [
        'Mix all ingredients to make batter.',
        'Pour onto hot skillet.',
        'Cook both sides until golden.',
        'Serve with syrup.',
      ],
      isFavorite: false,
    },
    {
      id: 7,
      title: 'Veggie Stir Fry',
      description: 'Quick and healthy stir-fried vegetables with soy sauce.',
      imageUrl: 'https://cookieandkate.com/images/2019/10/vegetarian-teriyaki-stir-fry-with-noodles-recipe-1.jpg',
      prepTime: 10,
      cookTime: 10,
      servings: 2,
      cuisine: 'Asian',
      mealType: 'Dinner',
      ingredients: [
        '1 cup broccoli',
        '1 bell pepper, sliced',
        '1 carrot, julienned',
        '2 tbsp soy sauce',
        '1 tbsp sesame oil',
      ],
      instructions: [
        'Heat oil in a wok.',
        'Add vegetables and stir fry for 5–7 minutes.',
        'Add soy sauce and cook 2 more minutes.',
      ],
      isFavorite: false,
    },
    {
      id: 8,
      title: 'Chocolate Milkshake',
      description: 'Rich chocolate shake with ice cream and whipped cream.',
      imageUrl: 'https://cookieandkate.com/images/2019/01/hot-chocolate-recipe-2.jpg',
      prepTime: 5,
      cookTime: 0,
      servings: 1,
      cuisine: 'American',
      mealType: 'Shakes',
      ingredients: [
        '1 cup milk',
        '2 scoops chocolate ice cream',
        '2 tbsp chocolate syrup',
        'Whipped cream (optional)',
      ],
      instructions: [
        'Blend milk, ice cream, and syrup until smooth.',
        'Top with whipped cream and serve.',
      ],
      isFavorite: false,
    },
    {
      id: 9,
      title: 'Caesar Salad',
      description: 'Crisp romaine lettuce with Caesar dressing and croutons.',
      imageUrl: 'https://cookieandkate.com/images/2021/05/homemade-caesar-salad.jpg',
      prepTime: 10,
      cookTime: 0,
      servings: 2,
      cuisine: 'Italian',
      mealType: 'Lunch',
      ingredients: [
        '2 cups romaine lettuce',
        '1/4 cup Caesar dressing',
        '1/4 cup croutons',
        'Grated parmesan cheese',
      ],
      instructions: [
        'Toss lettuce with dressing.',
        'Top with croutons and cheese.',
        'Serve chilled.',
      ],
      isFavorite: false,
    },
    {
      id: 10,
      title: 'Grilled Cheese Sandwich',
      description: 'Golden and crispy grilled bread with melted cheese inside.',
      imageUrl: 'https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_860,ar_3:2/v1/img/recipes/63/73/7/zGh9lvcURg6Pa58wVFfM_DSC00352.jpg',
      prepTime: 5,
      cookTime: 5,
      servings: 1,
      cuisine: 'American',
      mealType: 'Lunch',
      ingredients: [
        '2 slices of bread',
        '2 slices of cheese',
        'Butter',
      ],
      instructions: [
        'Butter the bread on both sides.',
        'Place cheese between the slices of bread.',
        'Grill in a skillet until golden and cheese is melted.',
      ],
      isFavorite: false,
    },
    {
      id: 11,
      title: 'Pasta Primavera',
      description: 'A fresh pasta dish with colorful vegetables and a light olive oil sauce.',
      imageUrl: 'https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_860,ar_3:2/v1/img/recipes/52/49/4/pic6f8zTo.jpg',
      prepTime: 15,
      cookTime: 10,
      servings: 4,
      cuisine: 'Italian',
      mealType: 'Dinner',
      ingredients: [
        '12 oz pasta',
        '1 cup cherry tomatoes',
        '1 cup bell peppers',
        '1 cup zucchini',
        'Olive oil',
        'Garlic',
        'Parmesan cheese',
      ],
      instructions: [
        'Cook pasta according to package instructions.',
        'Sauté vegetables in olive oil until tender.',
        'Toss pasta with vegetables and garlic.',
        'Top with parmesan cheese before serving.',
      ],
      isFavorite: false,
    },
    {
      id: 12,
      title: 'Chicken Caesar Wrap',
      description: 'A hearty wrap with grilled chicken, romaine lettuce, Caesar dressing, and parmesan.',
      imageUrl: 'https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_860,ar_3:2/v1/img/recipes/12/88/89/picePrGIX.jpg',
      prepTime: 10,
      cookTime: 10,
      servings: 2,
      cuisine: 'American',
      mealType: 'Lunch',
      ingredients: [
        '2 chicken breasts',
        '1 cup romaine lettuce',
        '1/4 cup Caesar dressing',
        '2 large tortillas',
        'Grated parmesan cheese',
      ],
      instructions: [
        'Grill chicken breasts and slice them thinly.',
        'Toss lettuce with Caesar dressing.',
        'Place chicken and lettuce in tortillas.',
        'Top with parmesan cheese and roll the wrap.',
      ],
      isFavorite: false,
    },
    {
      id: 13,
      title: 'Vegetable Stir Fry',
      description: 'A vibrant stir fry of assorted vegetables in a savory soy sauce.',
      imageUrl: 'https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_860,ar_3:2/v1/img/recipes/95/57/1/01493771908.jpeg',
      prepTime: 15,
      cookTime: 10,
      servings: 4,
      cuisine: 'Asian',
      mealType: 'Dinner',
      ingredients: [
        '1 cup broccoli',
        '1 cup bell peppers',
        '1 cup carrots',
        '1/4 cup soy sauce',
        '2 tbsp sesame oil',
        '1 clove garlic',
        '1 tsp ginger',
      ],
      instructions: [
        'Stir fry vegetables in sesame oil until tender.',
        'Add garlic and ginger and cook for 1 minute.',
        'Pour in soy sauce and cook for another 2 minutes.',
        'Serve hot with rice or noodles.',
      ],
      isFavorite: false,
    },
    
  ];  